llm:
  api_key: "YOUR_API_KEY"
  base_url: "https://api.openai.com/v1"
  role_prompt: "You are a reason expert."
run:
  prepare: true  # true 执行数据清洗，false 跳过
  runs: 5     # 评估循环次数
  max_workers: 5

generation:
  model: "gpt-4o"
  prompt_template: "Describe this image in natural language:"
  validation_threshold: 0
  max_attempts: 20
  max_workers: 512
  max_tokens: 256
  temperature: 0.6

evaluation:
  model: "gpt-4o"
  prompt: "You are a visual reasoning expert. Answer the question based on the image. Answer: yes or no. Then provide a step-by-step reasoning process."
  temperature: 0.0
  is_classification: True

paths:
  main_dir: "datasets/GQA/without_image/"
  raw_data: "raw_data.csv"
  clean_data: "clean_data.csv"
  result: "result.csv"
