llm:
  api_key: "YOUR_API_KEY"
  base_url: "http://localhost:8001/v1"
  role_prompt: "You are a seasoned plant pathologist for solanaceous crops."
run:
  prepare: false  # true 执行数据清洗，false 跳过
  runs: 5      # 评估循环次数
  max_workers: 5

generation:
  model: "gpt-4o"
  prompt_template: "Describe this image in natural language:"
  validation_threshold: 0
  max_attempts: 5
  max_workers: 200
  max_tokens: 4096
  temperature: 0.6

evaluation:
  model: "Qwen/Qwen2.5-VL-72B-Instruct-AWQ"#
#  prompt: "You are an expert plant pathologist who diagnoses tomato foliar diseases. Decide whether it shows early blight or late blight: reply yes if it is early blight and no if it is late blight. Answer: yes or no.
#  Then explain the reasons for the answer."
  prompt: "You are an expert plant pathologist who diagnoses tomato foliar diseases. Decide whether it shows early blight or late blight: reply yes if it is early blight and no if it is late blight. Answer: yes or no. 
  Then provide a step-by-step reasoning process."
  temperature: 0.0
  is_classification: True

paths:
  main_dir: "datasets/PlantVillage/"
  raw_data: "raw_data.csv"
  clean_data: "clean_data.csv"
  result: "result.csv"
